name: Build and Deploy Angular

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Baixando o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configurando Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        
      # Instalando dependências do projeto
      - name: Install dependencies
        run: |
          npm install

      # Executando o build do Angular
      - name: Build Angular project
        run: |
          npm run build --prod

      # Deploy para GitHub Pages (utilizando o Angular CLI)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.1.0
        with:
          branch: gh-pages        # Branch onde será publicado
          folder: dist/meu-site-angular  # Caminho onde o build é gerado
          token: ${{ secrets.GITHUB_TOKEN }} # Usar o token do GitHub

          